name: Build LaTeX and Deploy PDF

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-full

      - name: Compile PDF
        run: pdflatex main.tex

      - name: Prepare pages folder
        run: |
          mkdir public
          mv main.pdf public/index.pdf

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
